CREATE TABLE IF NOT EXISTS permitdocuments (

documentId  VARCHAR(22) NOT NULL,
region  VARCHAR(22) NOT NULL,
documentType  VARCHAR(60) NOT NULL,
subject VARCHAR(3000) NOT NULL,
category  VARCHAR(15) NOT NULL,
customer VARCHAR(450) NOT NULL,
techSupervision VARCHAR(255) NOT NULL,
designer VARCHAR(350) NOT NULL,
supervision VARCHAR(250) NOT NULL,
contractor VARCHAR(655) NOT NULL,
landInfo VARCHAR(500) NOT NULL,
month VARCHAR(2) NOT NULL,
year VARCHAR(4) NOT NULL,
timestamp TIMESTAMP NOT NULL DEFAULT now(),
md5 VARCHAR(32)  NOT NULL,

PRIMARY KEY (md5)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;